name: Release

on:
  release:
    types:
    - published
  schedule:
  - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  release:
    name: Release
    uses: OpenTTD/actions/.github/workflows/rw-entry-release-baseset.yml@v5
    secrets: inherit
    with:
      apt-packages: git
      name: opengfx2
      pip-packages: nml pillow blend-modes numpy skimage tqdm
      problem-matcher: .github/workflows/problem-matcher.json